// Postes (machines) de septembre-octobre 2026, déduits des couleurs du fichier Excel.
// Sert uniquement à /api/setup/assigner-postes.
export type MachineAssignment = { lastName: string; weekStart: string; dayOfWeek: number; period: "matin" | "soir"; machine: string };

export const SEPT_OCT_MACHINES: MachineAssignment[] = [
  { lastName: "CAREMENTRANT", weekStart: "2026-09-07", dayOfWeek: 0, period: "matin", machine: "Versa HD" },
  { lastName: "CAREMENTRANT", weekStart: "2026-09-07", dayOfWeek: 1, period: "matin", machine: "Versa HD" },
  { lastName: "CAREMENTRANT", weekStart: "2026-09-07", dayOfWeek: 2, period: "matin", machine: "Unity" },
  { lastName: "CAREMENTRANT", weekStart: "2026-09-07", dayOfWeek: 3, period: "matin", machine: "Versa HD" },
  { lastName: "CAREMENTRANT", weekStart: "2026-09-07", dayOfWeek: 4, period: "matin", machine: "Clinac" },
  { lastName: "CAREMENTRANT", weekStart: "2026-09-14", dayOfWeek: 0, period: "matin", machine: "Clinac" },
  { lastName: "CAREMENTRANT", weekStart: "2026-09-14", dayOfWeek: 1, period: "matin", machine: "Unity" },
  { lastName: "CAREMENTRANT", weekStart: "2026-09-14", dayOfWeek: 2, period: "matin", machine: "Unity" },
  { lastName: "CAREMENTRANT", weekStart: "2026-09-14", dayOfWeek: 3, period: "matin", machine: "Clinac" },
  { lastName: "CAREMENTRANT", weekStart: "2026-09-14", dayOfWeek: 4, period: "soir", machine: "Versa HD" },
  { lastName: "CAREMENTRANT", weekStart: "2026-09-21", dayOfWeek: 0, period: "matin", machine: "Unity" },
  { lastName: "CAREMENTRANT", weekStart: "2026-09-21", dayOfWeek: 1, period: "matin", machine: "Unity" },
  { lastName: "CAREMENTRANT", weekStart: "2026-09-21", dayOfWeek: 3, period: "matin", machine: "Versa HD" },
  { lastName: "CAREMENTRANT", weekStart: "2026-09-21", dayOfWeek: 4, period: "soir", machine: "Versa HD" },
  { lastName: "CAREMENTRANT", weekStart: "2026-09-28", dayOfWeek: 0, period: "matin", machine: "Versa HD" },
  { lastName: "CAREMENTRANT", weekStart: "2026-09-28", dayOfWeek: 1, period: "soir", machine: "Scanner" },
  { lastName: "CAREMENTRANT", weekStart: "2026-09-28", dayOfWeek: 2, period: "matin", machine: "Unity" },
  { lastName: "CAREMENTRANT", weekStart: "2026-09-28", dayOfWeek: 3, period: "matin", machine: "Clinac" },
  { lastName: "CAREMENTRANT", weekStart: "2026-10-05", dayOfWeek: 0, period: "soir", machine: "Clinac" },
  { lastName: "CAREMENTRANT", weekStart: "2026-10-05", dayOfWeek: 1, period: "matin", machine: "Versa HD" },
  { lastName: "CAREMENTRANT", weekStart: "2026-10-05", dayOfWeek: 2, period: "matin", machine: "Versa HD" },
  { lastName: "CAREMENTRANT", weekStart: "2026-10-05", dayOfWeek: 3, period: "matin", machine: "Scanner" },
  { lastName: "CAREMENTRANT", weekStart: "2026-10-05", dayOfWeek: 4, period: "soir", machine: "Versa HD" },
  { lastName: "CAREMENTRANT", weekStart: "2026-10-12", dayOfWeek: 0, period: "soir", machine: "Unity" },
  { lastName: "CAREMENTRANT", weekStart: "2026-10-12", dayOfWeek: 1, period: "matin", machine: "Versa HD" },
  { lastName: "CAREMENTRANT", weekStart: "2026-10-12", dayOfWeek: 2, period: "matin", machine: "Unity" },
  { lastName: "CAREMENTRANT", weekStart: "2026-10-12", dayOfWeek: 4, period: "soir", machine: "Versa HD" },
  { lastName: "CAREMENTRANT", weekStart: "2026-10-26", dayOfWeek: 0, period: "matin", machine: "Versa HD" },
  { lastName: "CAREMENTRANT", weekStart: "2026-10-26", dayOfWeek: 1, period: "matin", machine: "Versa HD" },
  { lastName: "CAREMENTRANT", weekStart: "2026-10-26", dayOfWeek: 4, period: "soir", machine: "Versa HD" },
  { lastName: "CHARBONNEL", weekStart: "2026-08-31", dayOfWeek: 2, period: "matin", machine: "Unity" },
  { lastName: "CHARBONNEL", weekStart: "2026-08-31", dayOfWeek: 3, period: "matin", machine: "Clinac" },
  { lastName: "CHARBONNEL", weekStart: "2026-08-31", dayOfWeek: 4, period: "matin", machine: "Versa HD" },
  { lastName: "CHARBONNEL", weekStart: "2026-09-07", dayOfWeek: 0, period: "soir", machine: "Versa HD" },
  { lastName: "CHARBONNEL", weekStart: "2026-09-07", dayOfWeek: 1, period: "soir", machine: "Scanner" },
  { lastName: "CHARBONNEL", weekStart: "2026-09-07", dayOfWeek: 2, period: "soir", machine: "Versa HD" },
  { lastName: "CHARBONNEL", weekStart: "2026-09-14", dayOfWeek: 0, period: "matin", machine: "Unity" },
  { lastName: "CHARBONNEL", weekStart: "2026-09-14", dayOfWeek: 1, period: "matin", machine: "Clinac" },
  { lastName: "CHARBONNEL", weekStart: "2026-09-14", dayOfWeek: 2, period: "matin", machine: "Clinac" },
  { lastName: "CHARBONNEL", weekStart: "2026-09-14", dayOfWeek: 3, period: "matin", machine: "Scanner" },
  { lastName: "CHARBONNEL", weekStart: "2026-09-14", dayOfWeek: 4, period: "matin", machine: "Clinac" },
  { lastName: "CHARBONNEL", weekStart: "2026-09-21", dayOfWeek: 0, period: "soir", machine: "Versa HD" },
  { lastName: "CHARBONNEL", weekStart: "2026-09-21", dayOfWeek: 1, period: "soir", machine: "Scanner" },
  { lastName: "CHARBONNEL", weekStart: "2026-09-21", dayOfWeek: 2, period: "soir", machine: "Unity" },
  { lastName: "CHARBONNEL", weekStart: "2026-09-21", dayOfWeek: 4, period: "soir", machine: "Versa HD" },
  { lastName: "CHARBONNEL", weekStart: "2026-09-28", dayOfWeek: 0, period: "matin", machine: "Scanner" },
  { lastName: "CHARBONNEL", weekStart: "2026-09-28", dayOfWeek: 1, period: "matin", machine: "Versa HD" },
  { lastName: "CHARBONNEL", weekStart: "2026-09-28", dayOfWeek: 2, period: "matin", machine: "Clinac" },
  { lastName: "CHARBONNEL", weekStart: "2026-09-28", dayOfWeek: 3, period: "matin", machine: "Unity" },
  { lastName: "CHARBONNEL", weekStart: "2026-09-28", dayOfWeek: 4, period: "matin", machine: "Unity" },
  { lastName: "CHARBONNEL", weekStart: "2026-10-05", dayOfWeek: 0, period: "soir", machine: "Versa HD" },
  { lastName: "CHARBONNEL", weekStart: "2026-10-05", dayOfWeek: 2, period: "soir", machine: "Versa HD" },
  { lastName: "CHARBONNEL", weekStart: "2026-10-05", dayOfWeek: 3, period: "soir", machine: "Versa HD" },
  { lastName: "CHARBONNEL", weekStart: "2026-10-05", dayOfWeek: 4, period: "soir", machine: "Scanner" },
  { lastName: "CHARBONNEL", weekStart: "2026-10-12", dayOfWeek: 0, period: "matin", machine: "Clinac" },
  { lastName: "CHARBONNEL", weekStart: "2026-10-12", dayOfWeek: 1, period: "matin", machine: "Clinac" },
  { lastName: "CHARBONNEL", weekStart: "2026-10-12", dayOfWeek: 2, period: "matin", machine: "Clinac" },
  { lastName: "CHARBONNEL", weekStart: "2026-10-12", dayOfWeek: 3, period: "matin", machine: "Unity" },
  { lastName: "CHARBONNEL", weekStart: "2026-10-19", dayOfWeek: 0, period: "soir", machine: "Versa HD" },
  { lastName: "CHARBONNEL", weekStart: "2026-10-19", dayOfWeek: 1, period: "soir", machine: "Versa HD" },
  { lastName: "CHARBONNEL", weekStart: "2026-10-19", dayOfWeek: 2, period: "soir", machine: "Scanner" },
  { lastName: "CHARBONNEL", weekStart: "2026-10-19", dayOfWeek: 3, period: "soir", machine: "Versa HD" },
  { lastName: "CHARBONNEL", weekStart: "2026-10-19", dayOfWeek: 4, period: "soir", machine: "Versa HD" },
  { lastName: "CHAULIAC", weekStart: "2026-08-31", dayOfWeek: 1, period: "soir", machine: "Versa HD" },
  { lastName: "CHAULIAC", weekStart: "2026-08-31", dayOfWeek: 2, period: "matin", machine: "Unity" },
  { lastName: "CHAULIAC", weekStart: "2026-08-31", dayOfWeek: 3, period: "matin", machine: "Unity" },
  { lastName: "CHAULIAC", weekStart: "2026-08-31", dayOfWeek: 4, period: "soir", machine: "Versa HD" },
  { lastName: "CHAULIAC", weekStart: "2026-09-07", dayOfWeek: 0, period: "matin", machine: "Clinac" },
  { lastName: "CHAULIAC", weekStart: "2026-09-07", dayOfWeek: 1, period: "matin", machine: "Clinac" },
  { lastName: "CHAULIAC", weekStart: "2026-09-07", dayOfWeek: 2, period: "matin", machine: "Unity" },
  { lastName: "CHAULIAC", weekStart: "2026-09-07", dayOfWeek: 3, period: "soir", machine: "Versa HD" },
  { lastName: "CHAULIAC", weekStart: "2026-09-07", dayOfWeek: 4, period: "matin", machine: "Unity" },
  { lastName: "CHAULIAC", weekStart: "2026-09-14", dayOfWeek: 0, period: "soir", machine: "Versa HD" },
  { lastName: "CHAULIAC", weekStart: "2026-09-14", dayOfWeek: 1, period: "soir", machine: "Versa HD" },
  { lastName: "CHAULIAC", weekStart: "2026-09-14", dayOfWeek: 2, period: "matin", machine: "Versa HD" },
  { lastName: "CHAULIAC", weekStart: "2026-09-14", dayOfWeek: 3, period: "matin", machine: "Unity" },
  { lastName: "CHAULIAC", weekStart: "2026-09-14", dayOfWeek: 4, period: "matin", machine: "Versa HD" },
  { lastName: "CHAULIAC", weekStart: "2026-09-21", dayOfWeek: 1, period: "matin", machine: "Versa HD" },
  { lastName: "CHAULIAC", weekStart: "2026-09-21", dayOfWeek: 2, period: "matin", machine: "Versa HD" },
  { lastName: "CHAULIAC", weekStart: "2026-09-21", dayOfWeek: 3, period: "matin", machine: "Versa HD" },
  { lastName: "CHAULIAC", weekStart: "2026-09-21", dayOfWeek: 4, period: "matin", machine: "Unity" },
  { lastName: "CHAULIAC", weekStart: "2026-09-28", dayOfWeek: 0, period: "matin", machine: "Clinac" },
  { lastName: "CHAULIAC", weekStart: "2026-09-28", dayOfWeek: 1, period: "matin", machine: "Unity" },
  { lastName: "CHAULIAC", weekStart: "2026-09-28", dayOfWeek: 2, period: "soir", machine: "Versa HD" },
  { lastName: "CHAULIAC", weekStart: "2026-09-28", dayOfWeek: 3, period: "soir", machine: "Clinac" },
  { lastName: "CHAULIAC", weekStart: "2026-09-28", dayOfWeek: 4, period: "soir", machine: "Unity" },
  { lastName: "CHAULIAC", weekStart: "2026-10-05", dayOfWeek: 0, period: "matin", machine: "Versa HD" },
  { lastName: "CHAULIAC", weekStart: "2026-10-05", dayOfWeek: 1, period: "matin", machine: "Versa HD" },
  { lastName: "CHAULIAC", weekStart: "2026-10-05", dayOfWeek: 2, period: "matin", machine: "Unity" },
  { lastName: "CHAULIAC", weekStart: "2026-10-05", dayOfWeek: 4, period: "matin", machine: "Unity" },
  { lastName: "CHAULIAC", weekStart: "2026-10-12", dayOfWeek: 0, period: "matin", machine: "Unity" },
  { lastName: "CHAULIAC", weekStart: "2026-10-12", dayOfWeek: 1, period: "matin", machine: "Clinac" },
  { lastName: "CHAULIAC", weekStart: "2026-10-12", dayOfWeek: 2, period: "matin", machine: "Versa HD" },
  { lastName: "CHAULIAC", weekStart: "2026-10-26", dayOfWeek: 3, period: "matin", machine: "Versa HD" },
  { lastName: "DUMONT", weekStart: "2026-09-21", dayOfWeek: 1, period: "matin", machine: "Unity" },
  { lastName: "DUMONT", weekStart: "2026-09-28", dayOfWeek: 0, period: "matin", machine: "Unity" },
  { lastName: "DUMONT", weekStart: "2026-09-28", dayOfWeek: 1, period: "matin", machine: "Clinac" },
  { lastName: "DUMONT", weekStart: "2026-09-28", dayOfWeek: 2, period: "matin", machine: "Clinac" },
  { lastName: "DUMONT", weekStart: "2026-09-28", dayOfWeek: 3, period: "soir", machine: "Clinac" },
  { lastName: "DUMONT", weekStart: "2026-09-28", dayOfWeek: 4, period: "matin", machine: "Unity" },
  { lastName: "DUMONT", weekStart: "2026-10-05", dayOfWeek: 0, period: "matin", machine: "Clinac" },
  { lastName: "DUMONT", weekStart: "2026-10-05", dayOfWeek: 1, period: "matin", machine: "Clinac" },
  { lastName: "DUMONT", weekStart: "2026-10-05", dayOfWeek: 2, period: "matin", machine: "Unity" },
  { lastName: "DUMONT", weekStart: "2026-10-05", dayOfWeek: 3, period: "matin", machine: "Clinac" },
  { lastName: "DUMONT", weekStart: "2026-10-05", dayOfWeek: 4, period: "matin", machine: "Clinac" },
  { lastName: "DUMONT", weekStart: "2026-10-12", dayOfWeek: 0, period: "soir", machine: "Clinac" },
  { lastName: "DUMONT", weekStart: "2026-10-12", dayOfWeek: 1, period: "soir", machine: "Clinac" },
  { lastName: "DUMONT", weekStart: "2026-10-12", dayOfWeek: 2, period: "soir", machine: "Clinac" },
  { lastName: "DUMONT", weekStart: "2026-10-12", dayOfWeek: 3, period: "soir", machine: "Clinac" },
  { lastName: "DUMONT", weekStart: "2026-10-12", dayOfWeek: 4, period: "soir", machine: "Clinac" },
  { lastName: "DUMONT", weekStart: "2026-10-19", dayOfWeek: 0, period: "soir", machine: "Clinac" },
  { lastName: "DUMONT", weekStart: "2026-10-19", dayOfWeek: 1, period: "matin", machine: "Clinac" },
  { lastName: "DUMONT", weekStart: "2026-10-19", dayOfWeek: 2, period: "matin", machine: "Clinac" },
  { lastName: "DUMONT", weekStart: "2026-10-19", dayOfWeek: 4, period: "matin", machine: "Clinac" },
  { lastName: "DUMONT", weekStart: "2026-10-26", dayOfWeek: 0, period: "matin", machine: "Clinac" },
  { lastName: "DUMONT", weekStart: "2026-10-26", dayOfWeek: 1, period: "matin", machine: "Clinac" },
  { lastName: "DUMONT", weekStart: "2026-10-26", dayOfWeek: 2, period: "matin", machine: "Clinac" },
  { lastName: "DUMONT", weekStart: "2026-10-26", dayOfWeek: 4, period: "soir", machine: "Unity" },
  { lastName: "EL ZAYAT", weekStart: "2026-09-07", dayOfWeek: 0, period: "matin", machine: "Scanner" },
  { lastName: "EL ZAYAT", weekStart: "2026-09-07", dayOfWeek: 1, period: "matin", machine: "Versa HD" },
  { lastName: "EL ZAYAT", weekStart: "2026-09-07", dayOfWeek: 3, period: "matin", machine: "Unity" },
  { lastName: "EL ZAYAT", weekStart: "2026-09-07", dayOfWeek: 4, period: "matin", machine: "Unity" },
  { lastName: "EL ZAYAT", weekStart: "2026-09-14", dayOfWeek: 0, period: "matin", machine: "Versa HD" },
  { lastName: "EL ZAYAT", weekStart: "2026-09-14", dayOfWeek: 1, period: "matin", machine: "Clinac" },
  { lastName: "EL ZAYAT", weekStart: "2026-09-14", dayOfWeek: 3, period: "matin", machine: "Clinac" },
  { lastName: "EL ZAYAT", weekStart: "2026-09-21", dayOfWeek: 0, period: "matin", machine: "Clinac" },
  { lastName: "EL ZAYAT", weekStart: "2026-09-21", dayOfWeek: 1, period: "matin", machine: "Clinac" },
  { lastName: "EL ZAYAT", weekStart: "2026-09-21", dayOfWeek: 3, period: "soir", machine: "Scanner" },
  { lastName: "EL ZAYAT", weekStart: "2026-09-21", dayOfWeek: 4, period: "matin", machine: "Unity" },
  { lastName: "EL ZAYAT", weekStart: "2026-09-28", dayOfWeek: 1, period: "matin", machine: "Unity" },
  { lastName: "EL ZAYAT", weekStart: "2026-09-28", dayOfWeek: 3, period: "matin", machine: "Versa HD" },
  { lastName: "EL ZAYAT", weekStart: "2026-09-28", dayOfWeek: 4, period: "matin", machine: "Clinac" },
  { lastName: "EL ZAYAT", weekStart: "2026-10-05", dayOfWeek: 0, period: "matin", machine: "Unity" },
  { lastName: "EL ZAYAT", weekStart: "2026-10-05", dayOfWeek: 1, period: "matin", machine: "Unity" },
  { lastName: "EL ZAYAT", weekStart: "2026-10-05", dayOfWeek: 3, period: "soir", machine: "Clinac" },
  { lastName: "EL ZAYAT", weekStart: "2026-10-05", dayOfWeek: 4, period: "soir", machine: "Clinac" },
  { lastName: "EL ZAYAT", weekStart: "2026-10-12", dayOfWeek: 3, period: "matin", machine: "Clinac" },
  { lastName: "EL ZAYAT", weekStart: "2026-10-26", dayOfWeek: 0, period: "matin", machine: "Clinac" },
  { lastName: "EL ZAYAT", weekStart: "2026-10-26", dayOfWeek: 1, period: "matin", machine: "Clinac" },
  { lastName: "EL ZAYAT", weekStart: "2026-10-26", dayOfWeek: 3, period: "matin", machine: "Clinac" },
  { lastName: "EL ZAYAT", weekStart: "2026-10-26", dayOfWeek: 4, period: "matin", machine: "Scanner" },
  { lastName: "FONTENEAU", weekStart: "2026-08-31", dayOfWeek: 1, period: "matin", machine: "Versa HD" },
  { lastName: "FONTENEAU", weekStart: "2026-08-31", dayOfWeek: 3, period: "matin", machine: "Versa HD" },
  { lastName: "FONTENEAU", weekStart: "2026-08-31", dayOfWeek: 4, period: "matin", machine: "Clinac" },
  { lastName: "FONTENEAU", weekStart: "2026-09-07", dayOfWeek: 0, period: "soir", machine: "Versa HD" },
  { lastName: "FONTENEAU", weekStart: "2026-09-07", dayOfWeek: 1, period: "soir", machine: "Versa HD" },
  { lastName: "FONTENEAU", weekStart: "2026-09-07", dayOfWeek: 2, period: "matin", machine: "Clinac" },
  { lastName: "FONTENEAU", weekStart: "2026-09-07", dayOfWeek: 3, period: "matin", machine: "Unity" },
  { lastName: "FONTENEAU", weekStart: "2026-09-14", dayOfWeek: 1, period: "matin", machine: "Versa HD" },
  { lastName: "FONTENEAU", weekStart: "2026-09-14", dayOfWeek: 2, period: "matin", machine: "Versa HD" },
  { lastName: "FONTENEAU", weekStart: "2026-09-21", dayOfWeek: 2, period: "matin", machine: "Versa HD" },
  { lastName: "FONTENEAU", weekStart: "2026-09-21", dayOfWeek: 3, period: "matin", machine: "Unity" },
  { lastName: "FONTENEAU", weekStart: "2026-09-28", dayOfWeek: 0, period: "soir", machine: "Versa HD" },
  { lastName: "FONTENEAU", weekStart: "2026-09-28", dayOfWeek: 3, period: "matin", machine: "Clinac" },
  { lastName: "FONTENEAU", weekStart: "2026-09-28", dayOfWeek: 4, period: "matin", machine: "Versa HD" },
  { lastName: "FONTENEAU", weekStart: "2026-10-05", dayOfWeek: 1, period: "soir", machine: "Clinac" },
  { lastName: "FONTENEAU", weekStart: "2026-10-05", dayOfWeek: 3, period: "matin", machine: "Versa HD" },
  { lastName: "FONTENEAU", weekStart: "2026-10-12", dayOfWeek: 0, period: "matin", machine: "Unity" },
  { lastName: "FONTENEAU", weekStart: "2026-10-12", dayOfWeek: 1, period: "soir", machine: "Versa HD" },
  { lastName: "FONTENEAU", weekStart: "2026-10-12", dayOfWeek: 4, period: "soir", machine: "Clinac" },
  { lastName: "FONTENEAU", weekStart: "2026-10-19", dayOfWeek: 1, period: "soir", machine: "Versa HD" },
  { lastName: "FONTENEAU", weekStart: "2026-10-19", dayOfWeek: 4, period: "matin", machine: "Versa HD" },
  { lastName: "FONTENEAU", weekStart: "2026-10-26", dayOfWeek: 0, period: "soir", machine: "Versa HD" },
  { lastName: "FONTENEAU", weekStart: "2026-10-26", dayOfWeek: 1, period: "soir", machine: "Versa HD" },
  { lastName: "FONTENEAU", weekStart: "2026-10-26", dayOfWeek: 4, period: "soir", machine: "Unity" },
  { lastName: "GAUTIER", weekStart: "2026-08-31", dayOfWeek: 1, period: "matin", machine: "Clinac" },
  { lastName: "GAUTIER", weekStart: "2026-08-31", dayOfWeek: 2, period: "soir", machine: "Unity" },
  { lastName: "GAUTIER", weekStart: "2026-08-31", dayOfWeek: 3, period: "matin", machine: "Versa HD" },
  { lastName: "GAUTIER", weekStart: "2026-08-31", dayOfWeek: 4, period: "matin", machine: "Unity" },
  { lastName: "GAUTIER", weekStart: "2026-09-07", dayOfWeek: 0, period: "matin", machine: "Unity" },
  { lastName: "GAUTIER", weekStart: "2026-09-07", dayOfWeek: 1, period: "soir", machine: "Unity" },
  { lastName: "GAUTIER", weekStart: "2026-09-07", dayOfWeek: 2, period: "matin", machine: "Versa HD" },
  { lastName: "GAUTIER", weekStart: "2026-09-07", dayOfWeek: 3, period: "soir", machine: "Versa HD" },
  { lastName: "GAUTIER", weekStart: "2026-09-14", dayOfWeek: 0, period: "matin", machine: "Versa HD" },
  { lastName: "GAUTIER", weekStart: "2026-09-14", dayOfWeek: 1, period: "soir", machine: "Versa HD" },
  { lastName: "GAUTIER", weekStart: "2026-09-14", dayOfWeek: 2, period: "matin", machine: "Unity" },
  { lastName: "GAUTIER", weekStart: "2026-09-14", dayOfWeek: 3, period: "matin", machine: "Versa HD" },
  { lastName: "GAUTIER", weekStart: "2026-09-14", dayOfWeek: 4, period: "matin", machine: "Versa HD" },
  { lastName: "GAUTIER", weekStart: "2026-09-21", dayOfWeek: 0, period: "soir", machine: "Versa HD" },
  { lastName: "GAUTIER", weekStart: "2026-09-21", dayOfWeek: 1, period: "soir", machine: "Versa HD" },
  { lastName: "GAUTIER", weekStart: "2026-09-21", dayOfWeek: 2, period: "matin", machine: "Clinac" },
  { lastName: "GAUTIER", weekStart: "2026-09-21", dayOfWeek: 3, period: "matin", machine: "Unity" },
  { lastName: "GAUTIER", weekStart: "2026-09-21", dayOfWeek: 4, period: "matin", machine: "Clinac" },
  { lastName: "GAUTIER", weekStart: "2026-09-28", dayOfWeek: 2, period: "matin", machine: "Versa HD" },
  { lastName: "GAUTIER", weekStart: "2026-09-28", dayOfWeek: 3, period: "matin", machine: "Versa HD" },
  { lastName: "GAUTIER", weekStart: "2026-09-28", dayOfWeek: 4, period: "matin", machine: "Clinac" },
  { lastName: "GAUTIER", weekStart: "2026-10-05", dayOfWeek: 0, period: "soir", machine: "Clinac" },
  { lastName: "GAUTIER", weekStart: "2026-10-05", dayOfWeek: 1, period: "soir", machine: "Unity" },
  { lastName: "GAUTIER", weekStart: "2026-10-05", dayOfWeek: 2, period: "matin", machine: "Clinac" },
  { lastName: "GAUTIER", weekStart: "2026-10-05", dayOfWeek: 3, period: "soir", machine: "Clinac" },
  { lastName: "GAUTIER", weekStart: "2026-10-05", dayOfWeek: 4, period: "soir", machine: "Clinac" },
  { lastName: "GAUTIER", weekStart: "2026-10-12", dayOfWeek: 0, period: "matin", machine: "Versa HD" },
  { lastName: "GAUTIER", weekStart: "2026-10-12", dayOfWeek: 1, period: "matin", machine: "Versa HD" },
  { lastName: "GAUTIER", weekStart: "2026-10-12", dayOfWeek: 2, period: "matin", machine: "Versa HD" },
  { lastName: "GAUTIER", weekStart: "2026-10-12", dayOfWeek: 4, period: "soir", machine: "Unity" },
  { lastName: "GAUTIER", weekStart: "2026-10-19", dayOfWeek: 0, period: "soir", machine: "Versa HD" },
  { lastName: "GAUTIER", weekStart: "2026-10-19", dayOfWeek: 1, period: "matin", machine: "Unity" },
  { lastName: "GAUTIER", weekStart: "2026-10-19", dayOfWeek: 2, period: "soir", machine: "Unity" },
  { lastName: "GAUTIER", weekStart: "2026-10-19", dayOfWeek: 3, period: "soir", machine: "Versa HD" },
  { lastName: "GAUTIER", weekStart: "2026-10-19", dayOfWeek: 4, period: "soir", machine: "Versa HD" },
  { lastName: "GAUTIER", weekStart: "2026-10-26", dayOfWeek: 1, period: "matin", machine: "Versa HD" },
  { lastName: "GAUTIER", weekStart: "2026-10-26", dayOfWeek: 2, period: "soir", machine: "Versa HD" },
  { lastName: "GAUTIER", weekStart: "2026-10-26", dayOfWeek: 3, period: "matin", machine: "Clinac" },
  { lastName: "GAUTIER", weekStart: "2026-10-26", dayOfWeek: 4, period: "matin", machine: "Unity" },
  { lastName: "GENET", weekStart: "2026-08-31", dayOfWeek: 1, period: "matin", machine: "Unity" },
  { lastName: "GENET", weekStart: "2026-08-31", dayOfWeek: 2, period: "matin", machine: "Versa HD" },
  { lastName: "GENET", weekStart: "2026-08-31", dayOfWeek: 3, period: "soir", machine: "Versa HD" },
  { lastName: "GENET", weekStart: "2026-08-31", dayOfWeek: 4, period: "matin", machine: "Versa HD" },
  { lastName: "GENET", weekStart: "2026-09-28", dayOfWeek: 0, period: "matin", machine: "Versa HD" },
  { lastName: "GENET", weekStart: "2026-09-28", dayOfWeek: 1, period: "matin", machine: "Versa HD" },
  { lastName: "GENET", weekStart: "2026-09-28", dayOfWeek: 3, period: "matin", machine: "Unity" },
  { lastName: "GENET", weekStart: "2026-09-28", dayOfWeek: 4, period: "matin", machine: "Versa HD" },
  { lastName: "GENET", weekStart: "2026-10-05", dayOfWeek: 0, period: "soir", machine: "Versa HD" },
  { lastName: "GENET", weekStart: "2026-10-05", dayOfWeek: 1, period: "soir", machine: "Versa HD" },
  { lastName: "GENET", weekStart: "2026-10-05", dayOfWeek: 2, period: "matin", machine: "Versa HD" },
  { lastName: "GENET", weekStart: "2026-10-05", dayOfWeek: 3, period: "soir", machine: "Unity" },
  { lastName: "GENET", weekStart: "2026-10-05", dayOfWeek: 4, period: "matin", machine: "Unity" },
  { lastName: "GENET", weekStart: "2026-10-12", dayOfWeek: 0, period: "soir", machine: "Versa HD" },
  { lastName: "GENET", weekStart: "2026-10-12", dayOfWeek: 1, period: "soir", machine: "Unity" },
  { lastName: "GENET", weekStart: "2026-10-12", dayOfWeek: 2, period: "matin", machine: "Unity" },
  { lastName: "GENET", weekStart: "2026-10-12", dayOfWeek: 3, period: "matin", machine: "Versa HD" },
  { lastName: "GENET", weekStart: "2026-10-12", dayOfWeek: 4, period: "soir", machine: "Versa HD" },
  { lastName: "GENET", weekStart: "2026-10-19", dayOfWeek: 0, period: "matin", machine: "Versa HD" },
  { lastName: "GENET", weekStart: "2026-10-19", dayOfWeek: 1, period: "matin", machine: "Unity" },
  { lastName: "GENET", weekStart: "2026-10-19", dayOfWeek: 2, period: "soir", machine: "Unity" },
  { lastName: "GENET", weekStart: "2026-10-19", dayOfWeek: 3, period: "matin", machine: "Versa HD" },
  { lastName: "GENET", weekStart: "2026-10-19", dayOfWeek: 4, period: "matin", machine: "Versa HD" },
  { lastName: "GENET", weekStart: "2026-10-26", dayOfWeek: 2, period: "matin", machine: "Versa HD" },
  { lastName: "GENET", weekStart: "2026-10-26", dayOfWeek: 3, period: "matin", machine: "Versa HD" },
  { lastName: "GENET", weekStart: "2026-10-26", dayOfWeek: 4, period: "matin", machine: "Versa HD" },
  { lastName: "HICQUEL", weekStart: "2026-08-31", dayOfWeek: 1, period: "matin", machine: "Clinac" },
  { lastName: "HICQUEL", weekStart: "2026-08-31", dayOfWeek: 2, period: "soir", machine: "Unity" },
  { lastName: "HICQUEL", weekStart: "2026-08-31", dayOfWeek: 3, period: "matin", machine: "Unity" },
  { lastName: "HICQUEL", weekStart: "2026-08-31", dayOfWeek: 4, period: "matin", machine: "Clinac" },
  { lastName: "HICQUEL", weekStart: "2026-09-07", dayOfWeek: 0, period: "soir", machine: "Scanner" },
  { lastName: "HICQUEL", weekStart: "2026-09-07", dayOfWeek: 1, period: "soir", machine: "Unity" },
  { lastName: "HICQUEL", weekStart: "2026-09-07", dayOfWeek: 2, period: "soir", machine: "Versa HD" },
  { lastName: "HICQUEL", weekStart: "2026-09-07", dayOfWeek: 3, period: "matin", machine: "Clinac" },
  { lastName: "HICQUEL", weekStart: "2026-09-07", dayOfWeek: 4, period: "matin", machine: "Clinac" },
  { lastName: "HICQUEL", weekStart: "2026-09-14", dayOfWeek: 0, period: "matin", machine: "Scanner" },
  { lastName: "HICQUEL", weekStart: "2026-09-14", dayOfWeek: 2, period: "soir", machine: "Versa HD" },
  { lastName: "HICQUEL", weekStart: "2026-09-14", dayOfWeek: 3, period: "matin", machine: "Unity" },
  { lastName: "HICQUEL", weekStart: "2026-09-14", dayOfWeek: 4, period: "matin", machine: "Clinac" },
  { lastName: "HICQUEL", weekStart: "2026-09-21", dayOfWeek: 0, period: "matin", machine: "Versa HD" },
  { lastName: "HICQUEL", weekStart: "2026-09-21", dayOfWeek: 2, period: "soir", machine: "Versa HD" },
  { lastName: "HICQUEL", weekStart: "2026-09-21", dayOfWeek: 3, period: "matin", machine: "Clinac" },
  { lastName: "HICQUEL", weekStart: "2026-09-21", dayOfWeek: 4, period: "matin", machine: "Versa HD" },
  { lastName: "HICQUEL", weekStart: "2026-09-28", dayOfWeek: 0, period: "matin", machine: "Clinac" },
  { lastName: "HICQUEL", weekStart: "2026-09-28", dayOfWeek: 1, period: "matin", machine: "Clinac" },
  { lastName: "HICQUEL", weekStart: "2026-09-28", dayOfWeek: 2, period: "soir", machine: "Scanner" },
  { lastName: "HICQUEL", weekStart: "2026-09-28", dayOfWeek: 3, period: "matin", machine: "Scanner" },
  { lastName: "HICQUEL", weekStart: "2026-10-05", dayOfWeek: 0, period: "soir", machine: "Unity" },
  { lastName: "HICQUEL", weekStart: "2026-10-05", dayOfWeek: 1, period: "matin", machine: "Scanner" },
  { lastName: "HICQUEL", weekStart: "2026-10-05", dayOfWeek: 2, period: "matin", machine: "Scanner" },
  { lastName: "HICQUEL", weekStart: "2026-10-05", dayOfWeek: 3, period: "matin", machine: "Versa HD" },
  { lastName: "HICQUEL", weekStart: "2026-10-12", dayOfWeek: 1, period: "soir", machine: "Unity" },
  { lastName: "HICQUEL", weekStart: "2026-10-12", dayOfWeek: 2, period: "soir", machine: "Clinac" },
  { lastName: "HICQUEL", weekStart: "2026-10-12", dayOfWeek: 3, period: "matin", machine: "Unity" },
  { lastName: "HICQUEL", weekStart: "2026-10-12", dayOfWeek: 4, period: "matin", machine: "Clinac" },
  { lastName: "HICQUEL", weekStart: "2026-10-19", dayOfWeek: 0, period: "soir", machine: "Clinac" },
  { lastName: "HICQUEL", weekStart: "2026-10-19", dayOfWeek: 1, period: "matin", machine: "Versa HD" },
  { lastName: "HICQUEL", weekStart: "2026-10-19", dayOfWeek: 2, period: "soir", machine: "Clinac" },
  { lastName: "HICQUEL", weekStart: "2026-10-19", dayOfWeek: 3, period: "matin", machine: "Scanner" },
  { lastName: "HICQUEL", weekStart: "2026-10-19", dayOfWeek: 4, period: "soir", machine: "Scanner" },
  { lastName: "HICQUEL", weekStart: "2026-10-26", dayOfWeek: 0, period: "matin", machine: "Scanner" },
  { lastName: "HICQUEL", weekStart: "2026-10-26", dayOfWeek: 2, period: "matin", machine: "Clinac" },
  { lastName: "HICQUEL", weekStart: "2026-10-26", dayOfWeek: 4, period: "soir", machine: "Versa HD" },
  { lastName: "LEDIEU", weekStart: "2026-08-31", dayOfWeek: 1, period: "matin", machine: "Scanner" },
  { lastName: "LEDIEU", weekStart: "2026-08-31", dayOfWeek: 2, period: "matin", machine: "Scanner" },
  { lastName: "LEDIEU", weekStart: "2026-08-31", dayOfWeek: 3, period: "matin", machine: "Clinac" },
  { lastName: "LEDIEU", weekStart: "2026-08-31", dayOfWeek: 4, period: "matin", machine: "Scanner" },
  { lastName: "LEDIEU", weekStart: "2026-09-14", dayOfWeek: 0, period: "matin", machine: "Unity" },
  { lastName: "LEDIEU", weekStart: "2026-09-14", dayOfWeek: 1, period: "matin", machine: "Unity" },
  { lastName: "LEDIEU", weekStart: "2026-09-14", dayOfWeek: 2, period: "matin", machine: "Scanner" },
  { lastName: "LEDIEU", weekStart: "2026-09-14", dayOfWeek: 4, period: "soir", machine: "Scanner" },
  { lastName: "LEDIEU", weekStart: "2026-09-21", dayOfWeek: 0, period: "matin", machine: "Scanner" },
  { lastName: "LEDIEU", weekStart: "2026-09-21", dayOfWeek: 2, period: "soir", machine: "Unity" },
  { lastName: "LEDIEU", weekStart: "2026-09-21", dayOfWeek: 3, period: "matin", machine: "Scanner" },
  { lastName: "LEDIEU", weekStart: "2026-09-28", dayOfWeek: 0, period: "soir", machine: "Scanner" },
  { lastName: "LEDIEU", weekStart: "2026-09-28", dayOfWeek: 2, period: "matin", machine: "Scanner" },
  { lastName: "LEDIEU", weekStart: "2026-09-28", dayOfWeek: 3, period: "soir", machine: "Unity" },
  { lastName: "LEDIEU", weekStart: "2026-09-28", dayOfWeek: 4, period: "matin", machine: "Scanner" },
  { lastName: "LEDIEU", weekStart: "2026-10-12", dayOfWeek: 0, period: "matin", machine: "Clinac" },
  { lastName: "LEDIEU", weekStart: "2026-10-12", dayOfWeek: 2, period: "matin", machine: "Clinac" },
  { lastName: "LEDIEU", weekStart: "2026-10-12", dayOfWeek: 3, period: "soir", machine: "Unity" },
  { lastName: "LEDIEU", weekStart: "2026-10-12", dayOfWeek: 4, period: "matin", machine: "Unity" },
  { lastName: "LEDIEU", weekStart: "2026-10-19", dayOfWeek: 0, period: "matin", machine: "Clinac" },
  { lastName: "LEDIEU", weekStart: "2026-10-19", dayOfWeek: 1, period: "matin", machine: "Scanner" },
  { lastName: "LEDIEU", weekStart: "2026-10-19", dayOfWeek: 2, period: "matin", machine: "Unity" },
  { lastName: "LEDIEU", weekStart: "2026-10-19", dayOfWeek: 3, period: "matin", machine: "Clinac" },
  { lastName: "LEDIEU", weekStart: "2026-10-19", dayOfWeek: 4, period: "matin", machine: "Scanner" },
  { lastName: "LEDIEU", weekStart: "2026-10-26", dayOfWeek: 1, period: "matin", machine: "Scanner" },
  { lastName: "LEDIEU", weekStart: "2026-10-26", dayOfWeek: 2, period: "matin", machine: "Scanner" },
  { lastName: "LEDIEU", weekStart: "2026-10-26", dayOfWeek: 3, period: "matin", machine: "Scanner" },
  { lastName: "LEDIEU", weekStart: "2026-10-26", dayOfWeek: 4, period: "soir", machine: "Scanner" },
  { lastName: "RENOU", weekStart: "2026-08-31", dayOfWeek: 1, period: "soir", machine: "Versa HD" },
  { lastName: "RENOU", weekStart: "2026-08-31", dayOfWeek: 2, period: "soir", machine: "Versa HD" },
  { lastName: "RENOU", weekStart: "2026-08-31", dayOfWeek: 3, period: "soir", machine: "Versa HD" },
  { lastName: "RENOU", weekStart: "2026-08-31", dayOfWeek: 4, period: "soir", machine: "Versa HD" },
  { lastName: "RENOU", weekStart: "2026-09-07", dayOfWeek: 0, period: "matin", machine: "Unity" },
  { lastName: "RENOU", weekStart: "2026-09-07", dayOfWeek: 1, period: "matin", machine: "Clinac" },
  { lastName: "RENOU", weekStart: "2026-09-07", dayOfWeek: 2, period: "matin", machine: "Scanner" },
  { lastName: "RENOU", weekStart: "2026-09-07", dayOfWeek: 3, period: "matin", machine: "Scanner" },
  { lastName: "RENOU", weekStart: "2026-09-07", dayOfWeek: 4, period: "matin", machine: "Scanner" },
  { lastName: "RENOU", weekStart: "2026-09-14", dayOfWeek: 0, period: "soir", machine: "Versa HD" },
  { lastName: "RENOU", weekStart: "2026-09-14", dayOfWeek: 2, period: "soir", machine: "Versa HD" },
  { lastName: "RENOU", weekStart: "2026-09-14", dayOfWeek: 3, period: "soir", machine: "Versa HD" },
  { lastName: "RENOU", weekStart: "2026-09-14", dayOfWeek: 4, period: "soir", machine: "Versa HD" },
  { lastName: "RENOU", weekStart: "2026-09-21", dayOfWeek: 0, period: "matin", machine: "Clinac" },
  { lastName: "RENOU", weekStart: "2026-09-21", dayOfWeek: 1, period: "matin", machine: "Clinac" },
  { lastName: "RENOU", weekStart: "2026-09-21", dayOfWeek: 2, period: "matin", machine: "Scanner" },
  { lastName: "RENOU", weekStart: "2026-09-21", dayOfWeek: 3, period: "matin", machine: "Clinac" },
  { lastName: "RENOU", weekStart: "2026-09-21", dayOfWeek: 4, period: "matin", machine: "Clinac" },
  { lastName: "RENOU", weekStart: "2026-09-28", dayOfWeek: 0, period: "soir", machine: "Versa HD" },
  { lastName: "RENOU", weekStart: "2026-09-28", dayOfWeek: 1, period: "soir", machine: "Versa HD" },
  { lastName: "RENOU", weekStart: "2026-09-28", dayOfWeek: 2, period: "soir", machine: "Versa HD" },
  { lastName: "RENOU", weekStart: "2026-10-05", dayOfWeek: 0, period: "matin", machine: "Unity" },
  { lastName: "RENOU", weekStart: "2026-10-05", dayOfWeek: 1, period: "matin", machine: "Clinac" },
  { lastName: "RENOU", weekStart: "2026-10-05", dayOfWeek: 2, period: "matin", machine: "Clinac" },
  { lastName: "RENOU", weekStart: "2026-10-05", dayOfWeek: 3, period: "matin", machine: "Clinac" },
  { lastName: "RENOU", weekStart: "2026-10-05", dayOfWeek: 4, period: "matin", machine: "Clinac" },
  { lastName: "RENOU", weekStart: "2026-10-12", dayOfWeek: 0, period: "soir", machine: "Versa HD" },
  { lastName: "RENOU", weekStart: "2026-10-12", dayOfWeek: 1, period: "soir", machine: "Scanner" },
  { lastName: "RENOU", weekStart: "2026-10-12", dayOfWeek: 2, period: "soir", machine: "Versa HD" },
  { lastName: "RENOU", weekStart: "2026-10-12", dayOfWeek: 3, period: "soir", machine: "Versa HD" },
  { lastName: "RENOU", weekStart: "2026-10-19", dayOfWeek: 0, period: "matin", machine: "Clinac" },
  { lastName: "RENOU", weekStart: "2026-10-19", dayOfWeek: 1, period: "matin", machine: "Clinac" },
  { lastName: "RENOU", weekStart: "2026-10-19", dayOfWeek: 2, period: "matin", machine: "Unity" },
  { lastName: "RENOU", weekStart: "2026-10-19", dayOfWeek: 3, period: "matin", machine: "Clinac" },
  { lastName: "RENOU", weekStart: "2026-10-19", dayOfWeek: 4, period: "matin", machine: "Clinac" },
  { lastName: "VINCENOT", weekStart: "2026-08-31", dayOfWeek: 1, period: "matin", machine: "Unity" },
  { lastName: "VINCENOT", weekStart: "2026-08-31", dayOfWeek: 2, period: "soir", machine: "Versa HD" },
  { lastName: "VINCENOT", weekStart: "2026-08-31", dayOfWeek: 3, period: "matin", machine: "Scanner" },
  { lastName: "VINCENOT", weekStart: "2026-08-31", dayOfWeek: 4, period: "matin", machine: "Unity" },
  { lastName: "VINCENOT", weekStart: "2026-09-21", dayOfWeek: 0, period: "matin", machine: "Versa HD" },
  { lastName: "VINCENOT", weekStart: "2026-09-21", dayOfWeek: 1, period: "matin", machine: "Versa HD" },
  { lastName: "VINCENOT", weekStart: "2026-09-21", dayOfWeek: 2, period: "soir", machine: "Versa HD" },
  { lastName: "VINCENOT", weekStart: "2026-09-21", dayOfWeek: 3, period: "soir", machine: "Versa HD" },
  { lastName: "VINCENOT", weekStart: "2026-09-21", dayOfWeek: 4, period: "matin", machine: "Scanner" },
  { lastName: "VINCENOT", weekStart: "2026-09-28", dayOfWeek: 0, period: "matin", machine: "Unity" },
  { lastName: "VINCENOT", weekStart: "2026-09-28", dayOfWeek: 1, period: "soir", machine: "Versa HD" },
  { lastName: "VINCENOT", weekStart: "2026-09-28", dayOfWeek: 2, period: "matin", machine: "Unity" },
  { lastName: "VINCENOT", weekStart: "2026-09-28", dayOfWeek: 3, period: "soir", machine: "Versa HD" },
  { lastName: "VINCENOT", weekStart: "2026-09-28", dayOfWeek: 4, period: "soir", machine: "Clinac" },
  { lastName: "VINCENOT", weekStart: "2026-10-05", dayOfWeek: 0, period: "matin", machine: "Scanner" },
  { lastName: "VINCENOT", weekStart: "2026-10-05", dayOfWeek: 1, period: "matin", machine: "Unity" },
  { lastName: "VINCENOT", weekStart: "2026-10-05", dayOfWeek: 3, period: "matin", machine: "Unity" },
  { lastName: "VINCENOT", weekStart: "2026-10-05", dayOfWeek: 4, period: "soir", machine: "Versa HD" },
  { lastName: "VINCENOT", weekStart: "2026-10-12", dayOfWeek: 0, period: "matin", machine: "Scanner" },
  { lastName: "VINCENOT", weekStart: "2026-10-12", dayOfWeek: 1, period: "matin", machine: "Unity" },
  { lastName: "VINCENOT", weekStart: "2026-10-12", dayOfWeek: 2, period: "soir", machine: "Unity" },
  { lastName: "VINCENOT", weekStart: "2026-10-12", dayOfWeek: 4, period: "matin", machine: "Versa HD" },
  { lastName: "VINCENOT", weekStart: "2026-10-19", dayOfWeek: 0, period: "matin", machine: "Scanner" },
  { lastName: "VINCENOT", weekStart: "2026-10-19", dayOfWeek: 2, period: "matin", machine: "Scanner" },
  { lastName: "VINCENOT", weekStart: "2026-10-26", dayOfWeek: 0, period: "soir", machine: "Versa HD" },
  { lastName: "VINCENOT", weekStart: "2026-10-26", dayOfWeek: 2, period: "soir", machine: "Versa HD" },
  { lastName: "VINCENOT", weekStart: "2026-10-26", dayOfWeek: 3, period: "soir", machine: "Scanner" },
  { lastName: "VINCENOT", weekStart: "2026-10-26", dayOfWeek: 4, period: "matin", machine: "Unity" },
  { lastName: "CHANEZ R", weekStart: "2026-08-31", dayOfWeek: 1, period: "soir", machine: "Scanner" },
  { lastName: "CHANEZ R", weekStart: "2026-08-31", dayOfWeek: 2, period: "matin", machine: "Versa HD" },
  { lastName: "CHANEZ R", weekStart: "2026-08-31", dayOfWeek: 3, period: "soir", machine: "Scanner" },
  { lastName: "CHANEZ R", weekStart: "2026-09-07", dayOfWeek: 0, period: "matin", machine: "Clinac" },
  { lastName: "CHANEZ R", weekStart: "2026-09-07", dayOfWeek: 1, period: "soir", machine: "Versa HD" },
  { lastName: "CHANEZ R", weekStart: "2026-09-07", dayOfWeek: 2, period: "matin", machine: "Clinac" },
  { lastName: "CHANEZ R", weekStart: "2026-09-07", dayOfWeek: 3, period: "matin", machine: "Clinac" },
  { lastName: "CHANEZ R", weekStart: "2026-09-14", dayOfWeek: 0, period: "matin", machine: "Clinac" },
  { lastName: "CHANEZ R", weekStart: "2026-09-14", dayOfWeek: 1, period: "soir", machine: "Scanner" },
  { lastName: "CHANEZ R", weekStart: "2026-09-14", dayOfWeek: 2, period: "matin", machine: "Clinac" },
  { lastName: "CHANEZ R", weekStart: "2026-09-14", dayOfWeek: 3, period: "soir", machine: "Versa HD" },
  { lastName: "CHANEZ R", weekStart: "2026-09-21", dayOfWeek: 0, period: "soir", machine: "Scanner" },
  { lastName: "CHANEZ R", weekStart: "2026-09-21", dayOfWeek: 1, period: "soir", machine: "Versa HD" },
  { lastName: "CHANEZ R", weekStart: "2026-09-21", dayOfWeek: 2, period: "matin", machine: "Clinac" },
  { lastName: "CHANEZ R", weekStart: "2026-09-21", dayOfWeek: 3, period: "soir", machine: "Versa HD" },
  { lastName: "CHANEZ R", weekStart: "2026-10-05", dayOfWeek: 0, period: "matin", machine: "Clinac" },
  { lastName: "CHANEZ R", weekStart: "2026-10-05", dayOfWeek: 1, period: "soir", machine: "Clinac" },
  { lastName: "CHANEZ R", weekStart: "2026-10-05", dayOfWeek: 3, period: "soir", machine: "Versa HD" },
  { lastName: "CHANEZ R", weekStart: "2026-10-12", dayOfWeek: 0, period: "soir", machine: "Clinac" },
  { lastName: "CHANEZ R", weekStart: "2026-10-12", dayOfWeek: 1, period: "soir", machine: "Clinac" },
  { lastName: "CHANEZ R", weekStart: "2026-10-12", dayOfWeek: 2, period: "soir", machine: "Unity" },
  { lastName: "CHANEZ R", weekStart: "2026-10-12", dayOfWeek: 3, period: "matin", machine: "Scanner" },
  { lastName: "CHANEZ R", weekStart: "2026-10-19", dayOfWeek: 0, period: "soir", machine: "Scanner" },
  { lastName: "CHANEZ R", weekStart: "2026-10-19", dayOfWeek: 1, period: "soir", machine: "Scanner" },
  { lastName: "CHANEZ R", weekStart: "2026-10-19", dayOfWeek: 2, period: "matin", machine: "Clinac" },
  { lastName: "CHANEZ R", weekStart: "2026-10-26", dayOfWeek: 0, period: "soir", machine: "Scanner" },
  { lastName: "CHANEZ R", weekStart: "2026-10-26", dayOfWeek: 2, period: "matin", machine: "Versa HD" },
  { lastName: "CHANEZ R", weekStart: "2026-10-26", dayOfWeek: 3, period: "soir", machine: "Versa HD" },
  { lastName: "FANTA C", weekStart: "2026-09-28", dayOfWeek: 3, period: "soir", machine: "Versa HD" },
  { lastName: "FANTA C", weekStart: "2026-09-28", dayOfWeek: 4, period: "soir", machine: "Clinac" },
  { lastName: "FANTA C", weekStart: "2026-10-05", dayOfWeek: 0, period: "matin", machine: "Versa HD" },
  { lastName: "FANTA C", weekStart: "2026-10-05", dayOfWeek: 1, period: "soir", machine: "Versa HD" },
  { lastName: "FANTA C", weekStart: "2026-10-05", dayOfWeek: 2, period: "soir", machine: "Versa HD" },
  { lastName: "FANTA C", weekStart: "2026-10-05", dayOfWeek: 3, period: "matin", machine: "Unity" },
  { lastName: "FANTA C", weekStart: "2026-10-05", dayOfWeek: 4, period: "matin", machine: "Versa HD" },
  { lastName: "FANTA C", weekStart: "2026-10-12", dayOfWeek: 0, period: "matin", machine: "Versa HD" },
  { lastName: "FANTA C", weekStart: "2026-10-12", dayOfWeek: 1, period: "soir", machine: "Versa HD" },
  { lastName: "FANTA C", weekStart: "2026-10-12", dayOfWeek: 2, period: "soir", machine: "Versa HD" },
  { lastName: "FANTA C", weekStart: "2026-10-12", dayOfWeek: 3, period: "soir", machine: "Versa HD" },
  { lastName: "FANTA C", weekStart: "2026-10-12", dayOfWeek: 4, period: "matin", machine: "Clinac" },
  { lastName: "FANTA C", weekStart: "2026-10-19", dayOfWeek: 0, period: "matin", machine: "Versa HD" },
  { lastName: "FANTA C", weekStart: "2026-10-19", dayOfWeek: 2, period: "soir", machine: "Clinac" },
  { lastName: "FANTA C", weekStart: "2026-10-19", dayOfWeek: 3, period: "matin", machine: "Versa HD" },
  { lastName: "FANTA C", weekStart: "2026-10-26", dayOfWeek: 0, period: "matin", machine: "Versa HD" },
  { lastName: "FANTA C", weekStart: "2026-10-26", dayOfWeek: 1, period: "soir", machine: "Versa HD" },
  { lastName: "FANTA C", weekStart: "2026-10-26", dayOfWeek: 3, period: "soir", machine: "Versa HD" },
  { lastName: "FANTA C", weekStart: "2026-10-26", dayOfWeek: 4, period: "matin", machine: "Versa HD" },
  { lastName: "JALALL B", weekStart: "2026-08-31", dayOfWeek: 1, period: "matin", machine: "Versa HD" },
  { lastName: "JALALL B", weekStart: "2026-09-07", dayOfWeek: 0, period: "matin", machine: "Versa HD" },
  { lastName: "JALALL B", weekStart: "2026-09-07", dayOfWeek: 2, period: "matin", machine: "Versa HD" },
  { lastName: "JALALL B", weekStart: "2026-09-07", dayOfWeek: 3, period: "matin", machine: "Versa HD" },
  { lastName: "JALALL B", weekStart: "2026-09-14", dayOfWeek: 1, period: "matin", machine: "Versa HD" },
  { lastName: "JALALL B", weekStart: "2026-09-14", dayOfWeek: 3, period: "matin", machine: "Versa HD" },
  { lastName: "JALALL B", weekStart: "2026-09-21", dayOfWeek: 4, period: "matin", machine: "Versa HD" },
  { lastName: "JALALL B", weekStart: "2026-10-05", dayOfWeek: 4, period: "matin", machine: "Versa HD" },
  { lastName: "JALALL B", weekStart: "2026-10-12", dayOfWeek: 4, period: "matin", machine: "Versa HD" },
  { lastName: "JALALL B", weekStart: "2026-10-19", dayOfWeek: 1, period: "matin", machine: "Versa HD" },
];
