// Proposition de planning novembre-décembre 2026 (brouillon), générée à partir des
// habilitations/contraintes transmises par la cadre. À revoir et publier semaine par
// semaine — les semaines restent en brouillon tant qu'elles ne sont pas publiées.
// Sert uniquement à /api/setup/assigner-postes.
export type ProposedShift = {
  importKey: string;
  weekStart: string;
  dayOfWeek: number;
  period: "matin" | "soir";
  machine: string | null;
  existing: boolean; // true = créneau déjà présent (importé), on ajoute juste le poste
  notes: string | null;
};

export const NOV_DEC_PROPOSAL: ProposedShift[] = [
  { importKey: "CAREMENTRANT", weekStart: "2026-11-02", dayOfWeek: 1, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-11-02", dayOfWeek: 3, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-11-02", dayOfWeek: 4, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-11-09", dayOfWeek: 1, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-11-09", dayOfWeek: 3, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-11-09", dayOfWeek: 4, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-11-16", dayOfWeek: 1, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-11-16", dayOfWeek: 3, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-11-16", dayOfWeek: 4, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-11-23", dayOfWeek: 1, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-11-23", dayOfWeek: 3, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-11-23", dayOfWeek: 4, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-11-30", dayOfWeek: 1, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-11-30", dayOfWeek: 3, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-11-30", dayOfWeek: 4, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-12-07", dayOfWeek: 1, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-12-07", dayOfWeek: 3, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-12-07", dayOfWeek: 4, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-12-14", dayOfWeek: 1, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-12-14", dayOfWeek: 3, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-12-14", dayOfWeek: 4, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-12-21", dayOfWeek: 4, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-12-28", dayOfWeek: 1, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-12-28", dayOfWeek: 3, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-11-02", dayOfWeek: 0, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-11-02", dayOfWeek: 1, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-11-02", dayOfWeek: 2, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-11-02", dayOfWeek: 3, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-11-02", dayOfWeek: 4, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-11-09", dayOfWeek: 0, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-11-09", dayOfWeek: 1, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-11-09", dayOfWeek: 2, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-11-09", dayOfWeek: 3, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-11-09", dayOfWeek: 4, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-11-16", dayOfWeek: 0, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-11-16", dayOfWeek: 1, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-11-16", dayOfWeek: 2, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-11-16", dayOfWeek: 3, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-11-16", dayOfWeek: 4, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-11-23", dayOfWeek: 0, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-11-23", dayOfWeek: 1, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-11-23", dayOfWeek: 2, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-11-23", dayOfWeek: 3, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-11-23", dayOfWeek: 4, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-11-30", dayOfWeek: 0, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-11-30", dayOfWeek: 1, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-11-30", dayOfWeek: 2, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-11-30", dayOfWeek: 3, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-11-30", dayOfWeek: 4, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-12-07", dayOfWeek: 0, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-12-07", dayOfWeek: 1, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-12-07", dayOfWeek: 2, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-12-07", dayOfWeek: 3, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-12-07", dayOfWeek: 4, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-12-14", dayOfWeek: 0, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-12-14", dayOfWeek: 1, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-12-14", dayOfWeek: 2, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-12-14", dayOfWeek: 3, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-12-14", dayOfWeek: 4, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-12-21", dayOfWeek: 0, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-12-21", dayOfWeek: 1, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-12-21", dayOfWeek: 2, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-12-21", dayOfWeek: 3, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-12-21", dayOfWeek: 4, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-12-28", dayOfWeek: 0, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-12-28", dayOfWeek: 1, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-12-28", dayOfWeek: 2, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "JALALL B", weekStart: "2026-12-28", dayOfWeek: 3, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-11-02", dayOfWeek: 0, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-11-02", dayOfWeek: 1, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-11-02", dayOfWeek: 2, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-11-02", dayOfWeek: 3, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-11-02", dayOfWeek: 4, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-11-09", dayOfWeek: 0, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-11-09", dayOfWeek: 1, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-11-09", dayOfWeek: 2, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-11-09", dayOfWeek: 3, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-11-09", dayOfWeek: 4, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-11-16", dayOfWeek: 0, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-11-16", dayOfWeek: 1, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-11-16", dayOfWeek: 2, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-11-16", dayOfWeek: 3, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-11-16", dayOfWeek: 4, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-11-23", dayOfWeek: 0, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-11-23", dayOfWeek: 1, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-11-23", dayOfWeek: 2, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-11-23", dayOfWeek: 3, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-11-23", dayOfWeek: 4, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-11-30", dayOfWeek: 0, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-11-30", dayOfWeek: 1, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-11-30", dayOfWeek: 2, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-11-30", dayOfWeek: 3, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-11-30", dayOfWeek: 4, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-12-07", dayOfWeek: 0, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-12-07", dayOfWeek: 1, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-12-07", dayOfWeek: 2, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-12-07", dayOfWeek: 3, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-12-07", dayOfWeek: 4, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-12-14", dayOfWeek: 0, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-12-14", dayOfWeek: 1, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-12-14", dayOfWeek: 2, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-12-14", dayOfWeek: 3, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-12-14", dayOfWeek: 4, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-12-21", dayOfWeek: 0, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-12-21", dayOfWeek: 1, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-12-21", dayOfWeek: 2, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-12-21", dayOfWeek: 3, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "LEDIEU", weekStart: "2026-12-21", dayOfWeek: 4, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-11-02", dayOfWeek: 0, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-11-02", dayOfWeek: 2, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-11-09", dayOfWeek: 0, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-11-09", dayOfWeek: 2, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-11-16", dayOfWeek: 0, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-11-16", dayOfWeek: 2, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-11-23", dayOfWeek: 0, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-11-23", dayOfWeek: 2, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-11-30", dayOfWeek: 0, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-11-30", dayOfWeek: 2, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-12-07", dayOfWeek: 0, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-12-07", dayOfWeek: 2, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-12-14", dayOfWeek: 0, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-12-14", dayOfWeek: 2, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-12-28", dayOfWeek: 0, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CAREMENTRANT", weekStart: "2026-12-28", dayOfWeek: 2, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-11-02", dayOfWeek: 0, period: "soir", machine: "Clinac", existing: true, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-11-02", dayOfWeek: 1, period: "soir", machine: "Clinac", existing: true, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-11-02", dayOfWeek: 2, period: "soir", machine: "Clinac", existing: true, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-11-02", dayOfWeek: 3, period: "soir", machine: "Clinac", existing: true, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-11-02", dayOfWeek: 4, period: "soir", machine: "Clinac", existing: true, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-11-09", dayOfWeek: 0, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-11-09", dayOfWeek: 1, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-11-09", dayOfWeek: 2, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-11-09", dayOfWeek: 3, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-11-09", dayOfWeek: 4, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-11-16", dayOfWeek: 0, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-11-16", dayOfWeek: 1, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-11-16", dayOfWeek: 2, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-11-16", dayOfWeek: 3, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-11-16", dayOfWeek: 4, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-11-23", dayOfWeek: 0, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-11-23", dayOfWeek: 1, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-11-23", dayOfWeek: 2, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-11-23", dayOfWeek: 3, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-11-23", dayOfWeek: 4, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-11-30", dayOfWeek: 0, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-11-30", dayOfWeek: 1, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-11-30", dayOfWeek: 2, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-11-30", dayOfWeek: 3, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-11-30", dayOfWeek: 4, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-12-07", dayOfWeek: 0, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-12-07", dayOfWeek: 1, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-12-07", dayOfWeek: 2, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-12-07", dayOfWeek: 3, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-12-07", dayOfWeek: 4, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-12-14", dayOfWeek: 0, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-12-14", dayOfWeek: 1, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-12-14", dayOfWeek: 2, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-12-14", dayOfWeek: 4, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-12-21", dayOfWeek: 0, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-12-21", dayOfWeek: 1, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-12-21", dayOfWeek: 2, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-12-21", dayOfWeek: 3, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHARBONNEL", weekStart: "2026-12-21", dayOfWeek: 4, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-11-02", dayOfWeek: 0, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-11-02", dayOfWeek: 1, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-11-02", dayOfWeek: 2, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-11-02", dayOfWeek: 3, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-11-02", dayOfWeek: 4, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-11-09", dayOfWeek: 0, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-11-09", dayOfWeek: 1, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-11-09", dayOfWeek: 2, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-11-09", dayOfWeek: 3, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-11-09", dayOfWeek: 4, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-11-16", dayOfWeek: 0, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-11-16", dayOfWeek: 1, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-11-16", dayOfWeek: 2, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-11-16", dayOfWeek: 3, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-11-16", dayOfWeek: 4, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-11-23", dayOfWeek: 0, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-11-23", dayOfWeek: 1, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-11-23", dayOfWeek: 2, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-11-23", dayOfWeek: 3, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-11-23", dayOfWeek: 4, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-11-30", dayOfWeek: 0, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-11-30", dayOfWeek: 1, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-11-30", dayOfWeek: 2, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-11-30", dayOfWeek: 3, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-11-30", dayOfWeek: 4, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-12-07", dayOfWeek: 0, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-12-07", dayOfWeek: 1, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-12-07", dayOfWeek: 2, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-12-07", dayOfWeek: 3, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-12-07", dayOfWeek: 4, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-12-14", dayOfWeek: 0, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-12-14", dayOfWeek: 1, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-12-14", dayOfWeek: 2, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-12-14", dayOfWeek: 3, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-12-14", dayOfWeek: 4, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-12-21", dayOfWeek: 0, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-12-21", dayOfWeek: 1, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-12-21", dayOfWeek: 2, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-12-21", dayOfWeek: 3, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-12-21", dayOfWeek: 4, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-12-28", dayOfWeek: 0, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-12-28", dayOfWeek: 1, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-12-28", dayOfWeek: 2, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "CHAULIAC", weekStart: "2026-12-28", dayOfWeek: 3, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-11-02", dayOfWeek: 0, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-11-02", dayOfWeek: 1, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-11-02", dayOfWeek: 2, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-11-02", dayOfWeek: 3, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-11-02", dayOfWeek: 4, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-11-09", dayOfWeek: 0, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-11-09", dayOfWeek: 1, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-11-09", dayOfWeek: 2, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-11-09", dayOfWeek: 3, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-11-09", dayOfWeek: 4, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-11-16", dayOfWeek: 0, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-11-16", dayOfWeek: 1, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-11-16", dayOfWeek: 2, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-11-16", dayOfWeek: 3, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-11-16", dayOfWeek: 4, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-11-23", dayOfWeek: 0, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-11-23", dayOfWeek: 1, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-11-23", dayOfWeek: 2, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-11-23", dayOfWeek: 3, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-11-23", dayOfWeek: 4, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-11-30", dayOfWeek: 0, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-11-30", dayOfWeek: 1, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-11-30", dayOfWeek: 2, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-11-30", dayOfWeek: 3, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-11-30", dayOfWeek: 4, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-12-07", dayOfWeek: 0, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-12-07", dayOfWeek: 1, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-12-07", dayOfWeek: 2, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-12-07", dayOfWeek: 3, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-12-07", dayOfWeek: 4, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-12-14", dayOfWeek: 0, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-12-14", dayOfWeek: 1, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-12-14", dayOfWeek: 2, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-12-14", dayOfWeek: 3, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-12-14", dayOfWeek: 4, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-12-21", dayOfWeek: 0, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-12-21", dayOfWeek: 1, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-12-21", dayOfWeek: 2, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-12-21", dayOfWeek: 3, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-12-21", dayOfWeek: 4, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-12-28", dayOfWeek: 0, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-12-28", dayOfWeek: 1, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-12-28", dayOfWeek: 2, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "DUMONT", weekStart: "2026-12-28", dayOfWeek: 3, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-11-02", dayOfWeek: 0, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-11-02", dayOfWeek: 1, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-11-02", dayOfWeek: 2, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-11-02", dayOfWeek: 3, period: "soir", machine: "Unity", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-11-02", dayOfWeek: 4, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-11-09", dayOfWeek: 2, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-11-16", dayOfWeek: 0, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-11-16", dayOfWeek: 1, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-11-16", dayOfWeek: 2, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-11-16", dayOfWeek: 3, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-11-16", dayOfWeek: 4, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-11-23", dayOfWeek: 0, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-11-23", dayOfWeek: 1, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-11-23", dayOfWeek: 2, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-11-23", dayOfWeek: 3, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-11-23", dayOfWeek: 4, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-11-30", dayOfWeek: 0, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-11-30", dayOfWeek: 1, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-11-30", dayOfWeek: 2, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-11-30", dayOfWeek: 3, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-11-30", dayOfWeek: 4, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-12-07", dayOfWeek: 0, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-12-07", dayOfWeek: 1, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-12-07", dayOfWeek: 2, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-12-07", dayOfWeek: 3, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-12-07", dayOfWeek: 4, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-12-14", dayOfWeek: 0, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-12-14", dayOfWeek: 1, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-12-21", dayOfWeek: 0, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-12-21", dayOfWeek: 1, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-12-21", dayOfWeek: 2, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-12-21", dayOfWeek: 3, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-12-21", dayOfWeek: 4, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-12-28", dayOfWeek: 0, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-12-28", dayOfWeek: 1, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-12-28", dayOfWeek: 2, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "GAUTIER", weekStart: "2026-12-28", dayOfWeek: 3, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "EL ZAYAT", weekStart: "2026-11-02", dayOfWeek: 0, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "EL ZAYAT", weekStart: "2026-11-02", dayOfWeek: 1, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "EL ZAYAT", weekStart: "2026-11-02", dayOfWeek: 3, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "EL ZAYAT", weekStart: "2026-11-02", dayOfWeek: 4, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "EL ZAYAT", weekStart: "2026-11-09", dayOfWeek: 0, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "EL ZAYAT", weekStart: "2026-11-09", dayOfWeek: 1, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "EL ZAYAT", weekStart: "2026-11-09", dayOfWeek: 2, period: "soir", machine: "Versa HD", existing: false, notes: "Temps partiel" },
  { importKey: "EL ZAYAT", weekStart: "2026-11-09", dayOfWeek: 4, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "EL ZAYAT", weekStart: "2026-11-16", dayOfWeek: 0, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "EL ZAYAT", weekStart: "2026-11-16", dayOfWeek: 1, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "EL ZAYAT", weekStart: "2026-11-16", dayOfWeek: 3, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "EL ZAYAT", weekStart: "2026-11-16", dayOfWeek: 4, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "EL ZAYAT", weekStart: "2026-11-23", dayOfWeek: 0, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "EL ZAYAT", weekStart: "2026-11-23", dayOfWeek: 1, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "EL ZAYAT", weekStart: "2026-11-23", dayOfWeek: 3, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "EL ZAYAT", weekStart: "2026-11-23", dayOfWeek: 4, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "EL ZAYAT", weekStart: "2026-11-30", dayOfWeek: 0, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "EL ZAYAT", weekStart: "2026-11-30", dayOfWeek: 1, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "EL ZAYAT", weekStart: "2026-11-30", dayOfWeek: 2, period: "soir", machine: "Versa HD", existing: false, notes: "Temps partiel" },
  { importKey: "EL ZAYAT", weekStart: "2026-11-30", dayOfWeek: 3, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "EL ZAYAT", weekStart: "2026-11-30", dayOfWeek: 4, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "EL ZAYAT", weekStart: "2026-12-07", dayOfWeek: 0, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "EL ZAYAT", weekStart: "2026-12-07", dayOfWeek: 1, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "EL ZAYAT", weekStart: "2026-12-07", dayOfWeek: 2, period: "soir", machine: "Versa HD", existing: false, notes: "Temps partiel" },
  { importKey: "EL ZAYAT", weekStart: "2026-12-07", dayOfWeek: 3, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "EL ZAYAT", weekStart: "2026-12-07", dayOfWeek: 4, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "EL ZAYAT", weekStart: "2026-12-14", dayOfWeek: 0, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "EL ZAYAT", weekStart: "2026-12-14", dayOfWeek: 1, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "EL ZAYAT", weekStart: "2026-12-14", dayOfWeek: 2, period: "soir", machine: "Versa HD", existing: false, notes: "Temps partiel" },
  { importKey: "EL ZAYAT", weekStart: "2026-12-14", dayOfWeek: 3, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "EL ZAYAT", weekStart: "2026-12-14", dayOfWeek: 4, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "EL ZAYAT", weekStart: "2026-12-21", dayOfWeek: 0, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "EL ZAYAT", weekStart: "2026-12-21", dayOfWeek: 1, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "EL ZAYAT", weekStart: "2026-12-21", dayOfWeek: 2, period: "soir", machine: "Versa HD", existing: false, notes: "Temps partiel" },
  { importKey: "EL ZAYAT", weekStart: "2026-12-21", dayOfWeek: 3, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "EL ZAYAT", weekStart: "2026-12-21", dayOfWeek: 4, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "FONTENEAU", weekStart: "2026-11-02", dayOfWeek: 0, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "FONTENEAU", weekStart: "2026-11-02", dayOfWeek: 1, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "FONTENEAU", weekStart: "2026-11-02", dayOfWeek: 2, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "FONTENEAU", weekStart: "2026-11-09", dayOfWeek: 2, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "FONTENEAU", weekStart: "2026-11-23", dayOfWeek: 0, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "FONTENEAU", weekStart: "2026-11-23", dayOfWeek: 1, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "FONTENEAU", weekStart: "2026-11-23", dayOfWeek: 2, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "FONTENEAU", weekStart: "2026-11-23", dayOfWeek: 3, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "FONTENEAU", weekStart: "2026-11-23", dayOfWeek: 4, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "FONTENEAU", weekStart: "2026-11-30", dayOfWeek: 0, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "FONTENEAU", weekStart: "2026-11-30", dayOfWeek: 1, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "FONTENEAU", weekStart: "2026-11-30", dayOfWeek: 2, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "FONTENEAU", weekStart: "2026-11-30", dayOfWeek: 3, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "FONTENEAU", weekStart: "2026-11-30", dayOfWeek: 4, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "FONTENEAU", weekStart: "2026-12-07", dayOfWeek: 0, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "FONTENEAU", weekStart: "2026-12-07", dayOfWeek: 1, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "FONTENEAU", weekStart: "2026-12-07", dayOfWeek: 2, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "FONTENEAU", weekStart: "2026-12-07", dayOfWeek: 3, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "FONTENEAU", weekStart: "2026-12-07", dayOfWeek: 4, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "FONTENEAU", weekStart: "2026-12-14", dayOfWeek: 0, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "FONTENEAU", weekStart: "2026-12-14", dayOfWeek: 1, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "FONTENEAU", weekStart: "2026-12-14", dayOfWeek: 2, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "FONTENEAU", weekStart: "2026-12-14", dayOfWeek: 3, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "FONTENEAU", weekStart: "2026-12-14", dayOfWeek: 4, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "FONTENEAU", weekStart: "2026-12-21", dayOfWeek: 4, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "FONTENEAU", weekStart: "2026-12-28", dayOfWeek: 0, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "FONTENEAU", weekStart: "2026-12-28", dayOfWeek: 1, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "FONTENEAU", weekStart: "2026-12-28", dayOfWeek: 2, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "FONTENEAU", weekStart: "2026-12-28", dayOfWeek: 3, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-11-02", dayOfWeek: 0, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-11-02", dayOfWeek: 1, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-11-02", dayOfWeek: 2, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-11-02", dayOfWeek: 3, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-11-02", dayOfWeek: 4, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-11-09", dayOfWeek: 0, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-11-09", dayOfWeek: 1, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-11-09", dayOfWeek: 2, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-11-09", dayOfWeek: 3, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-11-09", dayOfWeek: 4, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-11-23", dayOfWeek: 0, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-11-23", dayOfWeek: 1, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-11-23", dayOfWeek: 2, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-11-23", dayOfWeek: 3, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-11-23", dayOfWeek: 4, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-11-30", dayOfWeek: 0, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-11-30", dayOfWeek: 1, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-11-30", dayOfWeek: 2, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-11-30", dayOfWeek: 3, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-11-30", dayOfWeek: 4, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-12-07", dayOfWeek: 0, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-12-07", dayOfWeek: 1, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-12-07", dayOfWeek: 2, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-12-07", dayOfWeek: 3, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-12-07", dayOfWeek: 4, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-12-14", dayOfWeek: 0, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-12-14", dayOfWeek: 1, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-12-14", dayOfWeek: 2, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-12-14", dayOfWeek: 3, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-12-14", dayOfWeek: 4, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-12-21", dayOfWeek: 4, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-12-28", dayOfWeek: 0, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-12-28", dayOfWeek: 1, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-12-28", dayOfWeek: 2, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "GENET", weekStart: "2026-12-28", dayOfWeek: 3, period: "matin", machine: "Unity", existing: false, notes: null },
  { importKey: "HICQUEL", weekStart: "2026-11-02", dayOfWeek: 0, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "HICQUEL", weekStart: "2026-11-02", dayOfWeek: 1, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "HICQUEL", weekStart: "2026-11-02", dayOfWeek: 3, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "HICQUEL", weekStart: "2026-11-09", dayOfWeek: 0, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "HICQUEL", weekStart: "2026-11-09", dayOfWeek: 1, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "HICQUEL", weekStart: "2026-11-09", dayOfWeek: 3, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "HICQUEL", weekStart: "2026-11-16", dayOfWeek: 0, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "HICQUEL", weekStart: "2026-11-16", dayOfWeek: 1, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "HICQUEL", weekStart: "2026-11-16", dayOfWeek: 3, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "HICQUEL", weekStart: "2026-11-23", dayOfWeek: 0, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "HICQUEL", weekStart: "2026-11-23", dayOfWeek: 1, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "HICQUEL", weekStart: "2026-11-23", dayOfWeek: 3, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "HICQUEL", weekStart: "2026-11-30", dayOfWeek: 0, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "HICQUEL", weekStart: "2026-11-30", dayOfWeek: 1, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "HICQUEL", weekStart: "2026-11-30", dayOfWeek: 3, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "HICQUEL", weekStart: "2026-12-07", dayOfWeek: 0, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "HICQUEL", weekStart: "2026-12-07", dayOfWeek: 1, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "HICQUEL", weekStart: "2026-12-07", dayOfWeek: 3, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "HICQUEL", weekStart: "2026-12-14", dayOfWeek: 0, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "HICQUEL", weekStart: "2026-12-14", dayOfWeek: 1, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "HICQUEL", weekStart: "2026-12-14", dayOfWeek: 3, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "HICQUEL", weekStart: "2026-12-21", dayOfWeek: 0, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "HICQUEL", weekStart: "2026-12-21", dayOfWeek: 1, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "HICQUEL", weekStart: "2026-12-21", dayOfWeek: 3, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-11-02", dayOfWeek: 0, period: "matin", machine: "Clinac", existing: true, notes: null },
  { importKey: "RENOU", weekStart: "2026-11-02", dayOfWeek: 1, period: "matin", machine: "Scanner", existing: true, notes: null },
  { importKey: "RENOU", weekStart: "2026-11-02", dayOfWeek: 2, period: "matin", machine: "Scanner", existing: true, notes: null },
  { importKey: "RENOU", weekStart: "2026-11-02", dayOfWeek: 3, period: "matin", machine: "Scanner", existing: true, notes: null },
  { importKey: "RENOU", weekStart: "2026-11-02", dayOfWeek: 4, period: "matin", machine: "Scanner", existing: true, notes: null },
  { importKey: "RENOU", weekStart: "2026-11-09", dayOfWeek: 0, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-11-09", dayOfWeek: 1, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-11-09", dayOfWeek: 2, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-11-09", dayOfWeek: 3, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-11-09", dayOfWeek: 4, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-11-16", dayOfWeek: 0, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-11-16", dayOfWeek: 1, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-11-16", dayOfWeek: 2, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-11-16", dayOfWeek: 3, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-11-16", dayOfWeek: 4, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-11-23", dayOfWeek: 0, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-11-23", dayOfWeek: 1, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-11-23", dayOfWeek: 2, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-11-23", dayOfWeek: 3, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-11-23", dayOfWeek: 4, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-11-30", dayOfWeek: 0, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-11-30", dayOfWeek: 1, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-11-30", dayOfWeek: 2, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-11-30", dayOfWeek: 3, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-11-30", dayOfWeek: 4, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-12-07", dayOfWeek: 0, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-12-07", dayOfWeek: 1, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-12-07", dayOfWeek: 2, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-12-07", dayOfWeek: 3, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-12-07", dayOfWeek: 4, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-12-14", dayOfWeek: 0, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-12-14", dayOfWeek: 1, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-12-14", dayOfWeek: 2, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-12-14", dayOfWeek: 3, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-12-14", dayOfWeek: 4, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-12-21", dayOfWeek: 0, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-12-21", dayOfWeek: 1, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-12-21", dayOfWeek: 2, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-12-21", dayOfWeek: 3, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-12-21", dayOfWeek: 4, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-12-28", dayOfWeek: 0, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-12-28", dayOfWeek: 1, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-12-28", dayOfWeek: 2, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "RENOU", weekStart: "2026-12-28", dayOfWeek: 3, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-11-02", dayOfWeek: 0, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-11-02", dayOfWeek: 1, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-11-02", dayOfWeek: 2, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-11-02", dayOfWeek: 3, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-11-02", dayOfWeek: 4, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-11-09", dayOfWeek: 2, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-11-16", dayOfWeek: 0, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-11-16", dayOfWeek: 1, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-11-16", dayOfWeek: 2, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-11-16", dayOfWeek: 3, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-11-16", dayOfWeek: 4, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-11-23", dayOfWeek: 0, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-11-23", dayOfWeek: 1, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-11-23", dayOfWeek: 2, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-11-23", dayOfWeek: 3, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-11-23", dayOfWeek: 4, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-11-30", dayOfWeek: 0, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-11-30", dayOfWeek: 1, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-11-30", dayOfWeek: 2, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-11-30", dayOfWeek: 3, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-11-30", dayOfWeek: 4, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-12-07", dayOfWeek: 0, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-12-07", dayOfWeek: 1, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-12-07", dayOfWeek: 2, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-12-07", dayOfWeek: 3, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-12-07", dayOfWeek: 4, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-12-21", dayOfWeek: 0, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-12-21", dayOfWeek: 1, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-12-21", dayOfWeek: 2, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-12-21", dayOfWeek: 3, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-12-21", dayOfWeek: 4, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-12-28", dayOfWeek: 0, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-12-28", dayOfWeek: 1, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-12-28", dayOfWeek: 2, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "VINCENOT", weekStart: "2026-12-28", dayOfWeek: 3, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHANEZ R", weekStart: "2026-11-02", dayOfWeek: 0, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "CHANEZ R", weekStart: "2026-11-02", dayOfWeek: 1, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "CHANEZ R", weekStart: "2026-11-02", dayOfWeek: 2, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHANEZ R", weekStart: "2026-11-02", dayOfWeek: 3, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "CHANEZ R", weekStart: "2026-11-02", dayOfWeek: 4, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHANEZ R", weekStart: "2026-11-09", dayOfWeek: 0, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "CHANEZ R", weekStart: "2026-11-09", dayOfWeek: 1, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "CHANEZ R", weekStart: "2026-11-09", dayOfWeek: 2, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHANEZ R", weekStart: "2026-11-09", dayOfWeek: 3, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "CHANEZ R", weekStart: "2026-11-09", dayOfWeek: 4, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "CHANEZ R", weekStart: "2026-11-16", dayOfWeek: 0, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "CHANEZ R", weekStart: "2026-11-16", dayOfWeek: 1, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "CHANEZ R", weekStart: "2026-11-16", dayOfWeek: 2, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHANEZ R", weekStart: "2026-11-16", dayOfWeek: 3, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "CHANEZ R", weekStart: "2026-11-16", dayOfWeek: 4, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHANEZ R", weekStart: "2026-11-23", dayOfWeek: 0, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "CHANEZ R", weekStart: "2026-11-23", dayOfWeek: 1, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHANEZ R", weekStart: "2026-11-23", dayOfWeek: 2, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHANEZ R", weekStart: "2026-11-23", dayOfWeek: 3, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHANEZ R", weekStart: "2026-11-23", dayOfWeek: 4, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHANEZ R", weekStart: "2026-12-14", dayOfWeek: 0, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "CHANEZ R", weekStart: "2026-12-14", dayOfWeek: 1, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHANEZ R", weekStart: "2026-12-14", dayOfWeek: 2, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHANEZ R", weekStart: "2026-12-14", dayOfWeek: 3, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "CHANEZ R", weekStart: "2026-12-14", dayOfWeek: 4, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHANEZ R", weekStart: "2026-12-21", dayOfWeek: 0, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "CHANEZ R", weekStart: "2026-12-21", dayOfWeek: 1, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "CHANEZ R", weekStart: "2026-12-21", dayOfWeek: 2, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHANEZ R", weekStart: "2026-12-21", dayOfWeek: 3, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "CHANEZ R", weekStart: "2026-12-21", dayOfWeek: 4, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHANEZ R", weekStart: "2026-12-28", dayOfWeek: 0, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHANEZ R", weekStart: "2026-12-28", dayOfWeek: 1, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHANEZ R", weekStart: "2026-12-28", dayOfWeek: 2, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "CHANEZ R", weekStart: "2026-12-28", dayOfWeek: 3, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-11-02", dayOfWeek: 0, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-11-02", dayOfWeek: 1, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-11-02", dayOfWeek: 2, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-11-02", dayOfWeek: 3, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-11-02", dayOfWeek: 4, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-11-09", dayOfWeek: 0, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-11-09", dayOfWeek: 1, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-11-09", dayOfWeek: 2, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-11-09", dayOfWeek: 3, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-11-09", dayOfWeek: 4, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-11-16", dayOfWeek: 0, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-11-16", dayOfWeek: 1, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-11-16", dayOfWeek: 2, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-11-16", dayOfWeek: 3, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-11-16", dayOfWeek: 4, period: "soir", machine: "Versa HD", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-11-23", dayOfWeek: 0, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-11-23", dayOfWeek: 1, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-11-23", dayOfWeek: 2, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-11-23", dayOfWeek: 3, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-11-23", dayOfWeek: 4, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-11-30", dayOfWeek: 0, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-11-30", dayOfWeek: 1, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-11-30", dayOfWeek: 2, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-11-30", dayOfWeek: 3, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-11-30", dayOfWeek: 4, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-12-07", dayOfWeek: 0, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-12-07", dayOfWeek: 1, period: "matin", machine: "Versa HD", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-12-07", dayOfWeek: 2, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-12-07", dayOfWeek: 3, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-12-07", dayOfWeek: 4, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-12-14", dayOfWeek: 0, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-12-14", dayOfWeek: 1, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-12-14", dayOfWeek: 2, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-12-14", dayOfWeek: 3, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-12-14", dayOfWeek: 4, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-12-21", dayOfWeek: 0, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-12-21", dayOfWeek: 1, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-12-21", dayOfWeek: 2, period: "soir", machine: "Clinac", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-12-21", dayOfWeek: 3, period: "matin", machine: "Scanner", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-12-21", dayOfWeek: 4, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-12-28", dayOfWeek: 0, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-12-28", dayOfWeek: 1, period: "matin", machine: "Clinac", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-12-28", dayOfWeek: 2, period: "soir", machine: "Scanner", existing: false, notes: null },
  { importKey: "FANTA C", weekStart: "2026-12-28", dayOfWeek: 3, period: "matin", machine: "Scanner", existing: false, notes: null },
];
